version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9

conda:
  environment: doc/environment.yml

python:
  install:
    - method: pip
      path: .

submodules:
  include: all
