version: 2

sphinx:
  configuration: doc/conf.py

build:
  os: ubuntu-22.04
  apt_packages:
    - autoconf
    - automake
    - gfortran
    - libcfitsio-dev
    - libhealpix-cxx-dev
    - libsharp-dev
    - libtool
    - pkgconf
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

submodules:
  include: all
