# Based on http://conda.pydata.org/docs/travis.html,
# but modified so that we can test with Ubuntu's Python interpreter
# as well as Anaconda's.

language: python

sudo: false

addons:
    apt:
        packages:
        - pkg-config

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - USE_ANACONDA=false USE_PIP=false
  - USE_ANACONDA=false USE_PIP=true
  - USE_ANACONDA=true  USE_PIP=false
  - USE_ANACONDA=true  USE_PIP=true

# FIXME: The Ubuntu Python 3.4 package may use different default compiler flags.
# I think that Healpy needs to be built with the C compiler in C99 mode.
#
# For speed, only fully test internal cfitsio in Python 3.4

matrix:
  include:
    - python: 2.7
      env: USE_ANACONDA=true USE_PIP=false
      addons:
        apt:
          packages:
            - libcfitsio3-dev
    - python: 3.3
      env: USE_ANACONDA=true USE_PIP=false
      addons:
        apt:
          packages:
            - libcfitsio3-dev
    - python: 3.4
      env: USE_ANACONDA=false USE_PIP=false
      addons:
        apt:
          packages:
            - libcfitsio3-dev
    - python: 3.4
      env: USE_ANACONDA=false USE_PIP=true
      addons:
        apt:
          packages:
            - libcfitsio3-dev
    - python: 3.4
      env: USE_ANACONDA=true USE_PIP=false
      addons:
        apt:
          packages:
            - libcfitsio3-dev
    - python: 3.4
      env: USE_ANACONDA=true USE_PIP=true
      addons:
        apt:
          packages:
            - libcfitsio3-dev

before_install:
  # Use Matplotlib backend appropriate for headless rendering
  - |
    mkdir -p $HOME/.config/matplotlib && \
    echo 'backend: agg' > $HOME/.config/matplotlib/matplotlibrc

  # Install python and dependencies via system or anaconda
  - |
    if $USE_ANACONDA; then
      travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh \
        -O miniconda.sh && \
      bash miniconda.sh -b && \
      ~/miniconda/bin/conda create --yes -n anaconda_env \
        python=$TRAVIS_PYTHON_VERSION \
        setuptools pip numpy matplotlib && \
      source ~/miniconda/bin/activate anaconda_env && \
      travis_retry pip install pyfits cython pytest
    else
     travis_retry pip install --upgrade setuptools && \
     travis_retry pip install numpy matplotlib pyfits cython pytest
    fi

install:
  # Build first to create Cython sources
  # Then make source distribution
  # Uninstall things that are only needed when building from git
  # Finally, install from the source distribution using pip
  # how to remove this FIXME :    sudo apt-get -y remove autoconf automake pkg-config && \
  - |
    if $USE_PIP; then
      python setup.py build && \
      python setup.py sdist && \
      pip uninstall -y cython && \
      pip install dist/*.tar.gz
    else
      python setup.py install
    fi

script: python setup.py test
