# Based on http://conda.pydata.org/docs/travis.html,
# but modified so that we can test with Ubuntu's Python interpreter
# as well as Anaconda's.

language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  - USE_ANACONDA=false USE_PIP=false USE_EXTERNAL_CFITSIO=false
  - USE_ANACONDA=false USE_PIP=false USE_EXTERNAL_CFITSIO=true
  - USE_ANACONDA=false USE_PIP=true  USE_EXTERNAL_CFITSIO=false
  - USE_ANACONDA=false USE_PIP=true  USE_EXTERNAL_CFITSIO=true
  - USE_ANACONDA=true  USE_PIP=false USE_EXTERNAL_CFITSIO=false
  - USE_ANACONDA=true  USE_PIP=false USE_EXTERNAL_CFITSIO=true
  - USE_ANACONDA=true  USE_PIP=true  USE_EXTERNAL_CFITSIO=false
  - USE_ANACONDA=true  USE_PIP=true  USE_EXTERNAL_CFITSIO=true

# FIXME: The Ubuntu Python 3.4 package may use different default compiler flags.
# I think that Healpy needs to be built with the C compiler in C99 mode.
#
# For speed, only test internal cfitsio on certain versions of Python.

matrix:
  exclude:
    - python: 2.6
      env: USE_ANACONDA=false USE_PIP=false USE_EXTERNAL_CFITSIO=false
    - python: 2.6
      env: USE_ANACONDA=false USE_PIP=true  USE_EXTERNAL_CFITSIO=false
    - python: 2.6
      env: USE_ANACONDA=true  USE_PIP=false USE_EXTERNAL_CFITSIO=false
    - python: 2.6
      env: USE_ANACONDA=true  USE_PIP=true  USE_EXTERNAL_CFITSIO=false
    - python: 3.3
      env: USE_ANACONDA=false USE_PIP=false USE_EXTERNAL_CFITSIO=false
    - python: 3.3
      env: USE_ANACONDA=false USE_PIP=true  USE_EXTERNAL_CFITSIO=false
    - python: 3.3
      env: USE_ANACONDA=true  USE_PIP=false USE_EXTERNAL_CFITSIO=false
    - python: 3.3
      env: USE_ANACONDA=true  USE_PIP=true  USE_EXTERNAL_CFITSIO=false
    - python: 3.4
      env: USE_ANACONDA=false USE_PIP=false USE_EXTERNAL_CFITSIO=false
    - python: 3.4
      env: USE_ANACONDA=false USE_PIP=false USE_EXTERNAL_CFITSIO=true
    - python: 3.4
      env: USE_ANACONDA=false USE_PIP=true  USE_EXTERNAL_CFITSIO=false
    - python: 3.4
      env: USE_ANACONDA=false USE_PIP=true  USE_EXTERNAL_CFITSIO=true

before_install:
  # Use Matplotlib backend appropriate for headless rendering
  - |
    mkdir -p $HOME/.config/matplotlib && \
    echo 'backend: agg' > $HOME/.config/matplotlib/matplotlibrc

  # Install python and dependencies via system or anaconda
  - |
    if $USE_ANACONDA; then
      travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh \
        -O miniconda.sh && \
      bash miniconda.sh -b && \
      ~/miniconda/bin/conda create --yes -n anaconda_env \
        python=$TRAVIS_PYTHON_VERSION \
        setuptools pip numpy matplotlib astropy cython pytest && \
      source ~/miniconda/bin/activate anaconda_env
    else
     sudo apt-get -y install pkg-config && \
     travis_retry pip install --upgrade setuptools && \
     travis_retry pip install numpy matplotlib astropy cython pytest
    fi

  # Install cfitsio if necessary
  - if $USE_EXTERNAL_CFITSIO; then sudo apt-get -y install libcfitsio3-dev; fi

install:
  # Build first to create Cython sources
  # Then make source distribution
  # Uninstall things that are only needed when building from git
  # Finally, install from the source distribution using pip
  - |
    if $USE_PIP; then
      python setup.py build && \
      python setup.py sdist
      if $USE_ANACONDA; then
        conda uninstall -y cython
      else
        pip uninstall -y cython
      fi
      sudo apt-get -y remove autoconf automake pkg-config && \
      pip install dist/*.tar.gz
    else
      python setup.py install
    fi

script: python setup.py test
