cout <<
"Usage:\n"
"  alice2 ...\n"
"  where ... indicates any combination of the below optional parameters.\n"
"\n"
"  examples:\n"
"    alice2 -in wmap_ilc_3yr_v2_r6_sim.fits -nside 512 -ell 300 -xsz 800 -out test\n"
"    alice2 -in wmap_ilc_3yr_v2_r6_sim.fits -nside 512 -ell 300 -xsz 800 -out test_sos -sos\n"
"    alice2 -in wmap_ilc_3yr_v2_r6_sim.fits -nside 512 -ell 300 -xsz 500 -out test_orth -orth 1.0\n"
"\n"
"  [-in <fits file>] fits file contains the Q and U polarization\n"
"  components in the second and third columns.\n"
"\n"
"  [-temperature <fits file>] an optional fits file containing\n"
"  temperature data, if different temperature than that in the above\n"
"  file is desired\n"
"\n"
"  [-out <string>] string used as a prefix for output files\n"
"\n"
"  [-texture <fits file>] optional input background texture\n"
"\n"
"  [-nside <int>] nside of the background texture generated\n"
"\n"
"  [-ell <int>] ell value at which background texture has power\n"
"\n"
"  [-xsz <int>] x size: width of output images\n"
"\n"
"  [-flat] use a flat kernel for convolution, instead of a sinusoidal\n"
"  one.\n"
"\n"
"  [-steps <int>] number of steps to use for each line of the convolution\n"
"\n"
"  [-step_arcmin <float>] arcminutes for each step in the convoloution\n"
"\n"
"  [-threshold]\n"
"\n"
"  [-orth <float>] orthogonal projection.  <float> should be between 0.0 and 1.0;\n"
"  it determines the zoom.\n"
"\n"
"  [-alpha <float>] first euler angle\n"
"\n"
"  [-beta <float>] second euler angle\n"
"\n"
"  [-gamma <float>] third euler angle\n"
"\n"
"  [-col <int>] color table index\n"
"\n"
"  [-bar] plot a color bar at the bottom of the graphic\n"
"\n"
"  [-title <string>] title (in quotes) for the plot\n"
"\n"
"  [-fitsout <fits file>] output fits file that contains a texture.  No\n"
"  graphic is plotted.\n"
"\n"
"  [-texture2 <fits file>] a second texture, for interpolation\n"
"\n"
"  [-frames <int>] number of frames used in interpolation\n"
"\n"
"  [-sos] Science on a Sphere projection\n"
"\n"
"  [-min <float>] minimum value for the temperature scale\n"
"\n"
"  [-max <float>] maximum value for the temperature scale\n"
"\n"
"  [-polmin <float>] minimum value for the polarization magnitude\n"
"\n"
"  [-polmax <float>] maximum value for the polarization magnitude\n"
;
